On-site anisotropy terms involve one site and :math:`k` "entities". It should
map to the terms of the Hamiltonian that can be written as


.. math::

    \mathcal{H}_{on-site}
    =
    \sum_{k=1}^{\infty}
    C_{k,p(k)}
    \sum_{\mu_1, \alpha_1, i_1, \ldots, i_k}
    V_{\mu_1, \alpha_1}^{i_1, \ldots, i_k}
    \cdot
    X_{\mu_1; \alpha_1}^{i_1}
    \cdot
    \ldots
    \cdot
    X_{\mu_1; \alpha_1}^{i_k}